#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
import runpy
prefix = '/usr/lib/novapinyin/focal'
runpy.run_path(prefix + '/bin/novapinyin-runtime.py')['configure']()
globals().update(runpy.run_path(prefix + '/bin/novapinyin-manager', run_name=__name__))
